data:
  annotations: "data/annotations"
  datasets: "data/processed"
  raw_frames: "data/raw_frames"
  
models:
  ner: "models/text/ner_spacy"
  topic: "models/text/topic_seg"
  embeddings: "models/text/embeddings_SBERT"
  
outputs:
  logs: "logs"
  results: "results"
  
temp:
  cache: "temp/cache"